### ISSUE TITLE
Server launching fails when JAVA_HOME is not set in the launching process environment

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/galvan#10]
Unless JAVA_HOME is set in the launching process launching a server doesn't work because GALVAN won't set it for you.  I think the right thing here is to set it for the server process if it's not already set (setting it to point to the running VM obviously).

**Comment by jd0-sag** [comment]
This should be pretty straight-forward.

Detect JAVA_HOME:  System.getenv("JAVA_HOME")
If it is null, set the env var, for the inferior process to System.getProperty("java.home")

In my local tests, the difference between these are that JAVA_HOME points to the JDK root whereas java.home points to the JRE root.  At first glance, either should work since the start-tc-server.sh script is only using that to construct the path to the Java binary (and either of those /bin/java exists).

In either case, the harness output needs to mention that this is happening.
