### ISSUE TITLE
Galvan port allocation

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/galvan#103]
I'm having problems running up a server with Galvan because there is a bug.

PortChooser spends lots of effort finding a free non-ephemeral port to use, but Galvan's ConfigBuilder uses N*2 ports starting at that port (where N is the number of servers). PortChooser has not checked that all those ports will be free. On my Windows machine, the ephemeral port range is 1025-64510. PortChooser won't choose anything less than 1024, leaving very little space for any ports to be chosen. Port 1024 seems to be the one that PortChooser picks every time and I've got wininit.exe listening on 1025. Result: Unable to bind socket on address /0.0.0.0, port 1025, Address already in use: bind

I've reconfigured my ephemeral port range to be smaller and the acute problem has subsided, but there's no guarantee that PortChooser won't choose a port that doesn't have enough free ports after it - enough ports for ConfigBuilder's usage.

**Comment by jd0-sag** [comment]
Looks like `BasicHarnessEntry` is incorrectly calling `chooseRandomPort()` when it should be computing how many it needs and calling `chooseRandomPortRange()`.

Still won't make this 100% since the ports can't be _reserved_ for a later process but at least handles cases like this where it is clearly requesting the wrong number of ports.
