### ISSUE TITLE
Server launching requires the user to know upfront that a given range of ports are free.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/galvan#11]
Right now the server launching requires the user to know that a given range of ports are free in advance.  This will make running multiple tests in parallel awkward.  We could instead switch to using the PortChooser from core (used to choose healthchecker ports?) to assign open ports to each server.

**Comment by jd0-sag** [comment]
Looking at PortChooser, it looks like it would be racy:  2 processes check port X, both find it free and decide to use it, one binds it and the other can't understand the failure.

Is there something around how we use this which prevents that from happening?

Otherwise, so long as the parallel invocation is initiated from one point (one harness requesting multiple tests, not multiple harnesses requesting a single test), we can statically spread them.

**Comment by jd0-sag** [comment]
This was addressed by:  1c7ae67aea049ee30a8abb690262220ec69955d7
