### ISSUE TITLE
Client failure doesn't generate failure on entire test.

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#15]
Only stderr.log has error message but test finished as TEST RUN SUCCESSFUL!
In case of multiple clients the test is completed as success only if all clients has failures otherwise test hangs on synchronizeClient process

**Comment by jd0-sag** [comment]
As long as the error is such that the exit value of a client or server was non-zero, the harness should know it is a failure.  I will double-check that it is propagating that information up to the runner.

**Comment by jd0-sag** [comment]
Verified this:  if I make a client assert, it shows up in the logs but success is still declared.

Looking into it, now.

**Comment by jd0-sag** [comment]
It looks almost like it is the assertion handler is forcing us to return exit code 0 (success) since the harness correctly detects failure if I do something like "System.exit(99)".

I will have to find out why it is doing that since it seems wrong.  While galvan could also check for other eye-catchers in the output, as an error event, that means that any missing causes of failure would be flagged as passes.  Ideally, the exit value would be used to determine this (that is what programs are supposed to do).

**Comment by jd0-sag** [comment]
The problem is in TestClientStub:  it seemed to still have a catch from the earliest days of prototyping which was swallowing the assertion failures and letting the test return 0.

I removed that but also had to set the uncaught exception handler since we still have a daemon thread somewhere so we need to explicitly exit.

Just testing the fix, now, but it will probably be blocked on the existing PR against the repo.
