### ISSUE TITLE
request for some enhancements

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#18]
1) way to pass user defined or possibly validate  by framework info from harness to the tests. For example test need to know number of clients or server configuration at run time.

2)  way to identify which client runs on test code at runtime. This was achieved by  AbstractClientBase.getClientIndex() API in an old test framework.

3) we need write access to IClusterControl or possibly to something which will be available to the test interface to add user defined APIs.

**Comment by jd0-sag** [comment]
For now, 1 and 2 can remain constrained to the specific issues which have come up, recently:

* total number of clients running the test
* index of the currently running client
* target cluster URI

Part of the reason to constrain this is that it isn't clear where any other data would originate while all of these pieces of information are generated from within the framework.

I am not sure what (3) means (write access to IClusterControl - it is a control and synchronization interface so it is largely a "writing" operation - user defined APIs - what would this be?).  What are you specifically trying to accomplish which can't be done in the current system but could be done with these changes (maybe that will help me understand what the changes would look like)?

I will put together a few PRs (since this spans a few repos) to demonstrate what I mean.  The change will be large (as it adds more information to the ICommonTest interface, thus requiring updates to its implementators) but largely mechanical (mostly just plumbing through the new data).  The only behavioral change will be in the multi-process bridge between ClientRunner and TestClientStub, but that is fairly simple.

**Comment by yafeldman** [comment]
The word "write" in (3) is a typo please ignore this word. Sorry for that.

I am trying to ask you to expose possibility for users like me to be able to write own APIs once needed to control server. Instead of asking you or other developer to implement it. As example:  ClusterControl.crashPassives()  which is currently not exists in existing IClusterControl interface.

**Comment by jd0-sag** [comment]
The implementation at a lower level than IClusterControl is not generalized in any way so there would be no way to expose the details sufficient to add a control mechanism like that.

Any such functionality must be implemented in terms of the details of the underlying test framework so they will always need to be added to this interface, directly, and implemented for each supported test framework.
