### ISSUE TITLE
Galvan support for System.property fails under Linux

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/galvan#181]
The support added under PR #180 quotes the `-D` values added to `JAVA_OPTS`.  This works under Windows but does not under Linux ... Linux performs additional quoting during command line construction that causes the argument not to be recognized as a `-D` option and, instead, attempts to use it as the Java class to execute.

The quoting will be removed.  As a consequence, system property values containing characters requiring quoting won't be supported.

**Comment by mathieucarbou** [comment]
Hi @cljohnso @myronkscott : this issue is still opened and still exists I think:

in the monitoring service, I have put this class:

```
class Utils {
 private static final boolean ASSERT = Boolean.getBoolean("terracotta.management.assert");
[…]
}
```

I have a galvan test, that kills the active and wait for failover to complete in the setup() method. Here is the galvan rule:

```
public Cluster voltron = newCluster(2)
   .in(new File("target/galvan"))
   .withServiceFragment(resourceConfig)
   .withSystemProperty("terracotta.management.assert", "true")
   .build();
```

Sadly, ASSERT == false… The system property is either  not passed at all, or, not passed after a failover

**Comment by mathieucarbou** [comment]
UPDATE: this works: `.withTcProperty("terracotta.management.assert", "true")` and on Linux then ;-) we can close this.
