### ISSUE TITLE
Request for new IClusterControl APIs

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#27]
QA have the following control server APIs implemented in old framework. QA need something similar in galvan. Note currently all these APIs applies to all passives. Possibly there will be need for APIs applying to individual passives servers. 
-   startActives()
-   waitTillActivesDown(long timeoutInSeconds) 
-   waitForPassives()
-   crashActives()   -  kill process
-   waitTillPassivesDown(long timeoutInSeconds)
-   boolean arePassivesStandBy() - verified if all passives run
-   restartPassives()
-   restartActivesPassives();
-   GroupsData[] GroupsData() - Returns all the groups data for each mirror group

**Comment by jd0-sag** [comment]
What specific information do you use from GroupsData?  We also want to ensure that we are answering the high-level question being asked, since that makes it easier to keep a sufficiently portable interface.

In general, I want to make sure that we understand what the actual question is, as opposed to the specific details of how it was answered in the old framework.

**Comment by yafeldman** [comment]
With current test cases GroupsData() is only used to retrieve the number of stripes.

**Comment by jd0-sag** [comment]
One of the problems introduced by the "waitFor*" methods is that there is no way of saying "since when?".  For example, asking for the active to be crashed and then waiting for it to be "down" isn't so simple when a stripe would normally promote a new active, soon after the existing one is crashed.  If you ask too late, does that mean that you return immediately (since something went down, at some point in the past) or do you block for the next time it goes down (since it is currently up)?  Looking at existing tests which rely on this mechanism, they seem using fixed sleep intervals to try to avoid this problem.  That means that these tests are unreliable since they are timing-sensitive.

Waiting for _stable_ cluster states shouldn't be an issue, though:

* `waitForActive()` - Waits for a server to become active.  Returns immediately if there already is one.  Crashes galvan as a failure if called when no servers are running.
* `waitForRunningPassivesInStandby()` - Waits until all running servers which are not active enter passive standby state.  Returns immediately if they already are in this state.  Returns immediately if there are no running passives.

In terms of explicit control over starting/stopping specific servers, some softening will be required, since galvan doesn't have control over which server wins an election, for example.  I propose these explicit methods:

* `startOneServer()` - Starts a single server if there is one currently offline, from the initial configuration.  If all servers are running, does nothing.
* `startAllServers()` - Starts all servers which are currently offline, from the initial configuration.  If all servers are running, does nothing.
* `terminateActive()` - Forces the currently-active server to terminate, returning once it has.  Crashes galvan as a failure if called when there is no active server.
* `terminateOnePassive()` - Forces a currently-passive server to terminate, returning once it has.  If there are no running passive servers, does nothing.
* `terminateAllServers()` - Forces all currently-running servers to terminate, returning once they have.  If there are no running servers, does nothing.

It is probably possible to expose some sorts of inter-client interlocks, as well, but that idea is for later consideration and beyond the scope of these suggestions.  But, since they have a similar feel, I will at least state my current thinking:

* `clearClientFlag(String flagName)` - Clears the flag with the given name.  If the flag isn't set, does nothing.
* `setClientFlag(String flagName)` - Sets the flag with the given name, allowing any clients waiting for it to proceed (although they aren't required to acknowledge this in any specific time frame).  If the flag is already set, does nothing.
* `waitForClientFlag(String flagName)` - Blocks the calling client until the flag with the given name is set.  Any number of clients can wait on the same flag.
