### ISSUE TITLE
ServerProcess.start() returns before server's JVM process is launched on window

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/galvan#36]
As shown in the below code snippet, the start() method doesn't wait for JVM process to be launched on Windows. This can cause test to hang if the stop() is immediately invoked right after start. This problem was observed in one of the ehcache clustered tests causing the build to hang on Windows.

    // Wait for the server to enter started.
    synchronized (this) {
      if (TestHelpers.isWindows()){
        //windows start script doesn't emit this event, so skip it.
        this.isScriptReady = true;
      }
      while (!this.isScriptReady) {
        try {
          wait();
        } catch (InterruptedException e) {
          // We can't recover from interruption here.
          Assert.unexpected(e);
        }
      }
    }

**Comment by jd0-sag** [comment]
Are you sure that this was the cause of a hang?  The reason why this isn't done, on Windows, is that the start script is the process which we directly terminate, with taskkill, providing an option to kill the process tree.

On Unix, we only call the destroy() method on process object, which sends a signal to the script.  The Unix script is able to trap the signal to terminate the underlying JVM process.

This means that the Unix script introduces a timing hole between when the script starts and the server starts.  We made it emit this string once the underlying server started, so that galvan can treat the creation of both processes as one logical operation.

Since the Windows behavior relies on taskkill to do this sub-process termination, it shouldn't need this extra step.  I suspect that the hang was actually something different.

**Comment by jd0-sag** [comment]
This needs to be re-tested on the EhCache release build.

**Comment by esebasti** [comment]
I don't see this problem with the latest build. Closing it.
