### ISSUE TITLE
Enhance SynchronousProcessControl.internalWaitForActive()

### ISSUE THREAD

**Issue by ramsai1729** [Terracotta-OSS/galvan#41]
Currently we are using a hacky way to wait for a active, fix this properly 

relevant code snippet

```
 private void internalWaitForActive() {
    if (null == this.activeServer) {
      // First, walk the unknown servers.
      waitForAllUnknowns();
      // If we still have no active, walk the passives to see if one was promoted.
      if (null == this.activeServer) {
        checkAllPassivesState();

        // If we still can't find an active, do multiple retries with some timeout as it might take sometime for
        // other passives to become active (Note that this is a hacky way to fix the issue for now, we are going to
        // address this properly later)
        if(null == this.activeServer) {
          int retryCount = 30;
          while (retryCount-- != 0) {
            try {
              Thread.sleep(1000);
              checkAllPassivesState();
            } catch (InterruptedException e) {
              Assert.unexpected(e);
            }
          }
        }

        // See if we are still without an active.
        if (null == this.activeServer) {
          // If there is no active at this point, it probably means that there is something seriously wrong with the
          // server, such that it crashed while we were waiting for it to start.
          throw new IllegalStateException("Active process did not appear");
        }
      }
    }
  }
```

**Comment by jd0-sag** [comment]
The offending code mentioned exists in `SynchronousProcessControl`.  The problem is that the wait for the server state is in `ServerProcess`.

My plan is to refactor these other wait locations so that all thread `wait()` and `notify()` operations, relevant to Galvan, can be moved to `SynchronousProcessControl` (or potentially split out into a sub-module reachable from it).  This movement of all thread interlocking state under a single monitor will avoid some of the race conditions we have observed, will simplify the wait logic, and remove the need for hackish spin-loops such as this.

**Comment by jd0-sag** [comment]
Existing `wait()` points which must be moved to `SynchronousProcessControl`:

* `InterruptableClientManager` - manages the start-up of clients and waits for their termination states.  This should be fairly easily migrated as it already waits for the clients to complete, at each phase of the test (setup, test, destroy).  This means that the logic will be largely the same but needs to wait for the clients within `SynchronousProcessControl` instead of its own mechanism.
* `ServerProcess` - this one uses several wait points which will be somewhat more complex to move:  One waits for startup, one waits for PID to become available, one waits for termination.  This will require a deeper re-thinking to make sure that each wait point can be moved into `SynchronousProcessControl`.
* `TestStateManager` - this is used as the wait point for the external testing harness, so that it knows when the test is complete.  The right answer for this is probably to fold it into `SynchronousProcessControl` but the remaining question is whether it can immediately return when pass/fail state is known or if we also need to track some sort of "cleaned up" state so that return to the harness is only done when we are in a clean state.
* `BasicExternalCluster` - this can probably stay as is since it is just an interlock between the thread acting as the "the test harness" and the one running the client code.  These threads are distinct in order to permit asynchronous failure so this interlock is specific to their startup/shutdown coordination and largely external to the core Galvan logic.

**Comment by jd0-sag** [comment]
I have a prototype which seems to be working but there are still some intermittent errors which I am not sure are related (as there are some intermittent problems in our testing, at the moment).

The basic design is to create a multi-process interlock, which sits behind `SynchronousProcessControl`. This means that each of the calls through that can still be considered atomic, from the perspective of the client, while they may be internally based around a sequence of more primitive operations and asynchronous waits.

Once I have resolved these intermittent failures or concluded that they are unrelated, I will prepare a PR.
