### ISSUE TITLE
Galvan should not call System.exit from a TestHarness

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/galvan#69]
AbstractHarnessEntry calls System.exit from its UncaughtExceptionHandler.  This should probably not happen as it can cause strange behavior from things like surefire.

**Comment by jd0-sag** [comment]
Looking at this more closely, the current approach seems to be to catch uncaught errors in galvan, rather than actual test failures.

Instead of removing the `System.exit()`, we may just want to make it more descriptive and easier to find in the logs of a run so that these outstanding issues can be resolved.

I am trying to observe this to see what kinds of errors fall into this case but it is proving difficult.

**Comment by jd0-sag** [comment]
Going to return to this after some other work, to see if I can see us hit this code path.  The code is in `GalvanExceptionHandler`, which is in `AbstractHarnessEntry.java`.

**Comment by jd0-sag** [comment]
The System.exit() cases actually represent the point where Galvan bugs appear.  In these cases, there is no well-defined way to bring down all other processes.

I enhanced some of the logging around these cases so we can find them, when they occur:  02ec4d53d2b4d4bb3f08ee28a118b070f25fbd13
